name: ez_order_ezr
description: "Restaurant management made easy."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^14.1.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  image_picker_for_web: ^3.0.4
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pdf: ^3.10.8
  permission_handler: ^11.3.1
  printing: ^5.12.0
  random_string: ^2.3.1
  riverpod_annotation: ^2.3.5
  share_plus: ^9.0.0
  supabase_flutter: ^2.5.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.9
  change_app_package_name: ^1.2.0
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icono_final.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icono_final.jpg"
    background_color: "#000000"
    theme_color: "#000000"

flutter_native_splash:
  color: "#FF6A29"
  image: assets/icon/splash.png
  android_12:
    image: assets/icon/splash.png
    color: "#FF6A29"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
    - assets/icon/
    - assets/dotENV.env
